
#Generator Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	heatGenerator = "30"
	#Base energy storage (Joules).
	bioGenerator = "30"
	#Base energy storage (Joules).
	solarGenerator = "10"
	#Base energy storage (Joules).
	advancedSolarGenerator = "20"
	#Base energy storage (Joules).
	windGenerator = "4"

