
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "8"
	#Energy per operation tick (Joules).
	osmiumCompressor = "8"
	#Energy per operation tick (Joules).
	combiner = "50"
	#Energy per operation tick (Joules).
	crusher = "8"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "4"
	#Energy per operation tick (Joules).
	purificationChamber = "10"
	#Energy per operation tick (Joules).
	energizedSmelter = "4"
	#Energy per operation tick (Joules).
	digitalMiner = "100"
	#Energy per operation tick (Joules).
	electricPump = "4"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "2"
	#Energy per operation tick (Joules).
	oxidationChamber = "15"
	#Energy per operation tick (Joules).
	chemicalInfuser = "15"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "15"
	#Energy per operation tick (Joules).
	precisionSawmill = "8"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "16"
	#Energy per operation tick (Joules).
	chemicalWasher = "5"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "15"
	#Energy per operation tick (Joules).
	seismicVibrator = "10"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "2"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "8"
	#Energy per operation tick (Joules).
	laser = "10000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "8"
	#Energy per operation tick (Joules).
	modificationStation = "10"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "8"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "8"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "100000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "8"
	#Energy per operation tick (Joules).
	pigmentMixer = "4"
	#Energy per operation tick (Joules).
	paintingMachine = "4"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "5000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10"
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		teleporterDimensionPenalty = "10000"

