
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "40"
	#Base energy storage (Joules).
	osmiumCompressor = "40"
	#Base energy storage (Joules).
	combiner = "40"
	#Base energy storage (Joules).
	crusher = "40"
	#Base energy storage (Joules).
	metallurgicInfuser = "40"
	#Base energy storage (Joules).
	purificationChamber = "40"
	#Base energy storage (Joules).
	energizedSmelter = "40"
	#Base energy storage (Joules).
	digitalMiner = "200"
	#Base energy storage (Joules).
	electricPump = "40"
	#Base energy storage (Joules).
	chargePad = "1000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "40"
	#Base energy storage (Joules).
	oxidationChamber = "40"
	#Base energy storage (Joules).
	chemicalInfuser = "40"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "40"
	#Base energy storage (Joules).
	electrolyticSeparator = "40"
	#Base energy storage (Joules).
	precisionSawmill = "40"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "40"
	#Base energy storage (Joules).
	chemicalWasher = "40"
	#Base energy storage (Joules).
	chemicalCrystallizer = "40"
	#Base energy storage (Joules).
	seismicVibrator = "40"
	#Base energy storage (Joules).
	pressurizedReactionBase = "40"
	#Base energy storage (Joules).
	fluidicPlenisher = "40"
	#Base energy storage (Joules).
	laser = "2000000"
	#Base energy storage (Joules).
	laserAmplifier = "5000000000"
	#Base energy storage (Joules).
	laserTractorBeam = "5000000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "40000"
	#Base energy storage (Joules).
	teleporter = "5000000"
	#Base energy storage (Joules).
	modificationStation = "1000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "40"
	#Base energy storage (Joules).
	nutritionalLiquifier = "40"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "1000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "40"
	#Base energy storage (Joules).
	pigmentMixer = "40"
	#Base energy storage (Joules).
	paintingMachine = "40"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "1000000000"
	#Base energy storage (Joules).
	dimensionalStabilizer = "40000"

